#pragma once
#include <cstddef>
#include <cstdint>
#include <yyjson.h>
#include <zip.h>

struct abstract_file {
  bool is_file;
  char *path;
  union {
    zip_stat_t stat;
    FILE *file;
  } u;
};

struct abstract_memory {
  size_t size;
  char *data;
  zip_source_t *source;
};

extern char *home_dir;
extern char cwd_path[1024];
extern char formated_path[1024];
extern char formated_path_2[1024]; // updates more frequently, used internally in abstract_file functions

extern zip_t *open_archive;
extern zip_error_t *zerror;

abstract_memory abstract_memory_create(bool is_raw, void *data, size_t size);
bool abstract_memory_read_data(abstract_memory *memory);
void abstract_memory_free(abstract_memory *memory);

abstract_memory abstract_file_read(abstract_file *afile);
abstract_memory abstract_file_open_and_read(abstract_file *afile, const char *path);
bool abstract_file_close(abstract_file *afile);
bool abstract_file_write(abstract_file *afile, abstract_memory);
bool abstract_file_make_real(abstract_file *afile, abstract_memory *memory);

#define json_assert(cond, ...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        \
  if (!(cond)) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \
    fprintf(stderr, __VA_ARGS__);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     \
    return false;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     \
  }

#define json_assert2(cond, ...)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       \
  if (!(cond)) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \
    fprintf(stderr, __VA_ARGS__);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     \
    yjson_mut_doc_free(doc);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \
    return false;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     \
  }

#define json_iter_end() }

#define json_iter_arr(array_, var_, idx_)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             \
  yyjson_val *var_;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   \
  yyjson_arr_iter var_##_iter = yyjson_arr_iter_with((array_));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       \
  intptr_t idx_ = -1;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 \
  while ((var_ = yyjson_arr_iter_next(&var_##_iter))) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
    idx_++;

#define json_iter_obj(obj_, key_, val_)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
  yyjson_val *key_, *val_;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            \
  yyjson_obj_iter val_##_iter = yyjson_obj_iter_with((obj_));                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         \
  while ((key_ = yyjson_obj_iter_next(&val_##_iter))) {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               \
    val_ = yyjson_obj_iter_get_val(key_);

bool json_get_vector3(yyjson_val *val, float *x, float *y, float *z);

#ifdef _WIN32
#define SEP "\\"
#else
#define SEP "/"
#endif

#define ROOTDIR SEP ".reaktory" SEP
#define TMPDIR "tmp" SEP
#define MODELS_DIR "models" SEP
