#include "embeded/skybox.png.cpp"
#include "embeded/icon.png.cpp"
#include "embeded/icons.png.cpp"
#include "embeded/skybox.frag.glsl.cpp"
#include "embeded/skybox.vertex.glsl.cpp"
#include "embeded/cubemap.vs.cpp"
#include "embeded/cubemap.fs.cpp"
#include "embeded/skinning.vs.cpp"
#include "embeded/skinning.fs.cpp"
#include "embeded/skinning_colorpicker.fs.cpp"
#include "embeded/placeholder.png.cpp"

#include "embeded/fa.h"
#include "embeded/RobotoRegular.cpp"

#include "embeded/scene.json.cpp"
#include "embeded/data.txt.cpp"
#include "embeded/data.xlsx.cpp"
