#include "embeded/skybox.png.cpp"
#include "embeded/icon.png.cpp"
#include "embeded/icons.png.cpp"
#include "embeded/skybox.frag.glsl.cpp"
#include "embeded/skybox.vertex.glsl.cpp"
#include "embeded/cubemap.vs.cpp"
#include "embeded/cubemap.fs.cpp"
#include "embeded/skinning.vs.cpp"
#include "embeded/skinning.fs.cpp"

#include "embeded/fa.h"
#include "embeded/RobotoRegular.cpp"
